In [ ]:
!pip install -q transformers dataset accelerate

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import torch
print("GPU available:", torch.cuda.is_available())
print("GPU name: ", torch.cuda.get_device_name(0))

GPU available: True
GPU name:  Tesla T4

In [ ]:
from datasets import load_dataset
dataset=load_dataset("stanfordnlp/imdb")

print(dataset)
print(dataset["train"][0])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})
{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
model_name = "distilbert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(model_name,
                                                           num_labels=2
                                                           )

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
def tokenize_function(examples):
  return tokenizer(
      examples["text"],
      padding="max_length",    #makes all inputs same length
      truncation=True,       #cuts off text longer than 512 tokens
      max_length=512
  )

tokenized_datasets = dataset.map(tokenize_function, batched=True)
print(type(tokenized_datasets))

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

<class 'datasets.dataset_dict.DatasetDict'>

In [ ]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/my_model", #saves to my drive
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True     #uses GPU memory efficiently
)
trainer = Trainer(
    model=model,
    args = training_args,
    train_dataset = tokenized_datasets["train"],
    eval_dataset = tokenized_datasets["test"],
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=9375, training_loss=0.18922619750976563, metrics={'train_runtime': 1649.7695, 'train_samples_per_second': 45.461, 'train_steps_per_second': 5.683, 'total_flos': 9935054899200000.0, 'train_loss': 0.18922619750976563, 'epoch': 3.0})

In [ ]:
results = trainer.evaluate()
print(results)

# Save the final model to Drive
trainer.save_model("/content/drive/MyDrive/my_final_model")
print("Model saved!")

{'eval_loss': 0.2445184886455536}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model saved!

In [ ]:
from transformers import pipeline

classifier = pipeline(
    "text-classification",
    model="/content/drive/MyDrive/my_final_model",
    tokenizer=tokenizer
)

result = classifier("This movie was absolutely fantastic!")
print(result)   #should output LABEL_1 (positive) with high confidence

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'LABEL_1', 'score': 0.9975783228874207}]

In [ ]:
sentences = [
    "This movie was absolutely fantastic!",       # clearly positive
    "Worst film I have ever seen in my life.",     # clearly negative
    "It was okay, nothing special.",              # neutral — tricky!
    "The acting was great but the plot was weak." # mixed — very tricky!
]

results = classifier(sentences)
for sentence, result in zip(sentences, results):
    print(f"{result['label']} ({result['score']:.2%}) — {sentence}")

LABEL_1 (99.76%) — This movie was absolutely fantastic!
LABEL_0 (99.92%) — Worst film I have ever seen in my life.
LABEL_0 (99.86%) — It was okay, nothing special.
LABEL_0 (99.46%) — The acting was great but the plot was weak.

In [ ]:
trainer.model.save_pretrained("/content/drive/MyDrive/my_final_model")
tokenizer.save_pretrained("/content/drive/MyDrive/my_final_model")
print("Saved!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Saved!

In [3]:
from huggingface_hub import login
login(token="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")

In [4]:
# Step 2 — Reload model from Drive
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/my_final_model", local_files_only=True)
model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/my_final_model", local_files_only=True)

print("Model reloaded!")

OSError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/drive/MyDrive/my_final_model'. Use `repo_type` argument if needed.

In [5]:
# Cell 1 — Imports
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import torch

In [6]:
# Cell 2 — Load dataset
dataset = load_dataset("stanfordnlp/imdb")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/7.81k [00:00<?, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [8]:
# Cell 3 — Load model and tokenizer
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [9]:
# Cell 4 — Tokenize
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=512)

tokenized_datasets = dataset.map(tokenize_function, batched=True)
print("Tokenizing done!")

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   0%|          | 0/50000 [00:00<?, ? examples/s]

Tokenizing done!

In [10]:
# Cell 5 — Train
training_args = TrainingArguments(
    output_dir="./results",        # ← save checkpoints locally, NOT Drive
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=9375, training_loss=0.18414713155110676, metrics={'train_runtime': 1411.2464, 'train_samples_per_second': 53.145, 'train_steps_per_second': 6.643, 'total_flos': 9935054899200000.0, 'train_loss': 0.18414713155110676, 'epoch': 3.0})

In [11]:
# Cell 6 — Save PROPERLY to Drive this time
trainer.model.save_pretrained("/content/drive/MyDrive/my_final_model_v2")
tokenizer.save_pretrained("/content/drive/MyDrive/my_final_model_v2")

# Verify all files are there
import os
print(os.listdir("/content/drive/MyDrive/my_final_model_v2"))

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

['tokenizer.json', 'model.safetensors', 'config.json', 'tokenizer_config.json']

In [12]:
# Cell 7 — Login
from huggingface_hub import login
login(token="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")  # paste your token here

In [13]:
# Cell 8 — Reload from the new folder and push
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/my_final_model_v2", local_files_only=True)
model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/my_final_model_v2", local_files_only=True)

print("Model reloaded!")

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Model reloaded!

In [14]:
# Cell 9 — Push to Hub
model.push_to_hub("naruladhruv2006/movie-sentiment-analyzer")
tokenizer.push_to_hub("naruladhruv2006/movie-sentiment-analyzer")

print("✅ Done! Your model is live at:")
print("https://huggingface.co/naruladhruv2006/movie-sentiment-analyzer")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...nku2_u0/model.safetensors:   2%|1         | 4.21MB /  268MB

README.md:   0%|          | 0.00/5.17k [00:00<?, ?B/s]

✅ Done! Your model is live at:
https://huggingface.co/naruladhruv2006/movie-sentiment-analyzer